### ISSUE TITLE
Captcha1 python code does not work anymore

### ISSUE THREAD

**Issue by dieao** [james9909/PracticeCTF#2]
Hey Captcha1 code does not work anymore, have tried to update but still not working as getting post errors?

Traceback (most recent call last):
  File "C:/Users/eldri/PycharmProjects/cap/CAPTCHA1.py", line 30, in <module>
    while postSolution() == ":(":
  File "C:/Users/eldri/PycharmProjects/cap/CAPTCHA1.py", line 19, in postSolution
    captcha = Image.open(StringIO(captcha.content))
TypeError: initial_value must be str or None, not bytes

Updated code I have:

```
from PIL import Image
import pytesseract
import requests
from io import StringIO

def solve(captcha):
    return pytesseract.image_to_string(Image.open(captcha))[::-1]

def postSolution():
    url = "https://defendtheweb.net/playground/captcha1"
    login = "https://defendtheweb.net/auth"
    payload = {"username": "(mylogin)", "password": "(mypassword)"}

    s = requests.Session() # Start a session
    s.post(login, data=payload) # Login
    response = s.get(url).text # Get problem data
    captcha = s.get("https://defendtheweb.net/playground/captcha1")
    captcha = Image.open(StringIO(captcha.content))
    captcha.save("captcha1.png")
    solution = solve("C:/Users/eldri/PycharmProjects/cap/captcha1.png")
    payload = {"answer": solution}
    s.post(url, data=payload) # Post data
    response = s.get(url).text
    if ("Incomplete" in response):
        return ":("
    else:
        return "Sucessfully solved problem"

while postSolution() == ":(":
    postSolution()
print ("Solved!")
```

**Comment by dieao** [comment]
Also did you figure out crypt8? I have two sides but makes no sense?

**Comment by james9909** [comment]
For Captcha1, even if the code no longer works (might depend on your library/python versions, I think I was using Python 2 back then), the core concept for the solution should be the same (using an OCR library to extract the text from the images).
For Crypt8, I wasn't able to figure out the solution beyond what I have in the repository.
Hope this helps!

**Comment by dieao** [comment]
Hey James,

Thank you, I did amend the code to fit the updates but still getting the current issues, I will keep working on them. Great work btw, are you still on Defend the web? Previosuly Hackthis?
